"""Creating modeling for investments

Revision ID: 07c1bbeb7965
Revises: cda144881e95
Create Date: 2023-07-30 11:24:46.033381

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '07c1bbeb7965'
down_revision = 'cda144881e95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.drop_table('investment_updates')

    op.drop_constraint('investment_portfolio_investment_id_fkey', 'investment_portfolio', type_='foreignkey')
    op.create_foreign_key(None, 'investment_portfolio', 'investments', ['investment_id'], ['id'],
                          source_schema='finance', referent_schema='finance')

    op.drop_constraint('investment_rentability_investment_id_fkey', 'investment_rentability', type_='foreignkey')
    op.create_foreign_key(None, 'investment_rentability', 'investments', ['investment_id'], ['id'],
                          source_schema='finance', referent_schema='finance')

    op.drop_constraint('investment_transactions_investment_id_fkey', 'investment_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'investment_transactions', 'investments', ['investment_id'], ['id'],
                          source_schema='finance', referent_schema='finance')

    op.drop_column('investments', 'quantity')



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('quantity', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'investment_transactions', schema='finance', type_='foreignkey')
    op.create_foreign_key('investment_transactions_investment_id_fkey', 'investment_transactions', 'investments',
                          ['investment_id'], ['id'])
    op.drop_constraint(None, 'investment_rentability', schema='finance', type_='foreignkey')
    op.create_foreign_key('investment_rentability_investment_id_fkey', 'investment_rentability', 'investments',
                          ['investment_id'], ['id'])
    op.drop_constraint(None, 'investment_portfolio', schema='finance', type_='foreignkey')
    op.create_foreign_key('investment_portfolio_investment_id_fkey', 'investment_portfolio', 'investments',
                          ['investment_id'], ['id'])

    op.create_table('investment_updates',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('investment_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('update_date', sa.DATE(), autoincrement=False, nullable=False),
                    sa.Column('value', sa.NUMERIC(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'],
                                            name='investment_updates_investment_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='investment_updates_pkey')
                    )
    # ### end Alembic commands ###
