"""Initial alembic models

Revision ID: 109523718053
Revises: 
Create Date: 2023-07-29 17:58:25.372980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109523718053'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bank_statements_bank_id_fkey', 'bank_statements', type_='foreignkey')
    op.drop_constraint('bank_statements_category_id_fkey', 'bank_statements', type_='foreignkey')
    op.create_foreign_key(None, 'bank_statements', 'banks', ['bank_id'], ['id'], source_schema='finance', referent_schema='finance')
    op.create_foreign_key(None, 'bank_statements', 'category', ['category_id'], ['id'], source_schema='finance', referent_schema='finance')
    op.drop_constraint('investment_updates_investment_id_fkey', 'investment_updates', type_='foreignkey')
    op.create_foreign_key(None, 'investment_updates', 'investments', ['investment_id'], ['id'], source_schema='finance', referent_schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
