"""empty message

Revision ID: e9651718e0c1
Revises: 
Create Date: 2023-07-29 17:20:04.826921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9651718e0c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bank_statements_bank_id_fkey', 'bank_statements', type_='foreignkey')
    op.create_foreign_key(None, 'bank_statements', 'banks', ['bank_id'], ['id'], source_schema='finance', referent_schema='finance')
    op.drop_constraint('investment_updates_investment_id_fkey', 'investment_updates', type_='foreignkey')
    op.create_foreign_key(None, 'investment_updates', 'investments', ['investment_id'], ['id'], source_schema='finance', referent_schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'investment_updates', schema='finance', type_='foreignkey')
    op.create_foreign_key('investment_updates_investment_id_fkey', 'investment_updates', 'investments', ['investment_id'], ['id'])
    op.drop_constraint(None, 'bank_statements', schema='finance', type_='foreignkey')
    op.create_foreign_key('bank_statements_bank_id_fkey', 'bank_statements', 'banks', ['bank_id'], ['id'])
    # ### end Alembic commands ###
